version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: task-api-jaeger
    ports:
      - "16686:16686"  # UI
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:16686"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: .
    container_name: task-api
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /app
        read_only: true
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      jaeger:
        condition: service_healthy
    environment:
      - OTLP_ENDPOINT=http://jaeger:4317
      - ENVIRONMENT=development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:latest
    container_name: task-api-db
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: task-api-redis
    ports:
      - "6379:6379"
    volumes:
      - type: volume
        source: redis_data
        target: /data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:
